name: Security ğŸ‘®â€

on:
  schedule:
  - cron: "0 2 * * *"

jobs:
  security:

    runs-on: macos-latest

    steps:

    - name: Snyk ğŸ¶
      uses: snyk/actions@0.1.1

    - name: Release-Notes-Preview
      uses: snyk/release-notes-preview@v1.6.1

    - name: Test site for publicly known js vulnerabilities
      uses: lirantal/is-website-vulnerable@master
      with:
        scan-url: https://marcinxkaminski.github.io/face-expression-detector/
